// GENERATED by scripts/write-deployments-module.mjs — do not edit.
// Source of truth: deployments.json at the repo root, written by
// scripts/solana-init.mts.

export type NetworkId = 'devnet';

export const NETWORK_IDS = ['devnet'] as const;

export const DEFAULT_NETWORK: NetworkId = 'devnet';

export const DEPLOYMENTS = {
  devnet: {
    id: 'devnet',
    rpcUrl: 'https://api.devnet.solana.com',
    deployedAt: '2026-10-09T17:42:37.000Z',
    /** anchor/programs/changuito_escrow. */
    programId: 'BFa1gZL9kVVo8Mq5gaDRM5RiCG4NDiyHLbpymfXvLz9d',
    /** The escrow's Config PDA: resolver, treasury and mint. */
    config: 'BCcorb5CVL86uDQQT4fBusAcobXugFfTTM6ypL4bDBPh',
    /** Our devnet USDC. The resolver is its mint authority (the faucet). */
    usdcMint: 'BZ6CHGyRnuuGRxDmd1bCFdeUTCJGcGcWtUct1NMELG85',
    usdcDecimals: 6,
    usdcCode: 'USDC',
    /** Backend hot key: signs settle, refund and faucet mints. */
    resolver: '5zeMdzZCXkCHbTwvoxtEHRHCP5fe7MLc4fHgG54ENhUD',
    /** Where a settled order's USDC ends up. The app never signs for it. */
    treasury: '9TNtBk4RL2dmYdffqfudhLGc1DEtnHc8nmw7yWcD2ctc',
    treasuryToken: '6u1v9QbWXDA3WaU4j2c26sV9DomG7qRimNKch7VGnqcV',
  },
} as const;

/** Signatures that prove the deployment: deploy, initialize, smoke settle/refund. */
export const EVIDENCE = {
  "deploy": "4rNtLVRC8iQzHcnXVweNUkJ8yQYV4dBvnpw1rVKJQDFHNJRosMnWW3VuCE1FpFRuDjiVmQXNK7ycZvt73PoS6ixz",
  "initialize": "3ZQa77Kf83ddFtxG4oxxbWSAYCELEytnvwqzZVQkCxEuuixj45BAkjccZyfrnm6gEYsmj4iaee61ErXnWvyCNG6E",
  "smoke": {
    "fund": "7afnqiFKgQ3CgdwySV8qM7cqoxAJNbxPw7rwj2fx9jTZEtU11Fg7hSgUAaFEtzVQTrRG4P37Vx2BxqMTiSfkEhn",
    "settleOpen": "5ww3W1FQGjnspyzpcjFSEJjjMzwX9ZWXsmp7Hm4BjEpS7VSwSD1rgqzwaqU7o6q4mzeTPjAHmWaQFJzXtUkdotBE",
    "settle": "2Bmuhoev9j1HMFgi7RZ8mvsyvGt89CKwCNpvmc38NQnZhi2gsUPxYmjehgBtKrVSNZqxcfGuDn4CgH7BMbcr5o3B",
    "refundOpen": "4v7AZfCMsqX3pF169j8L6xcThNHGjYRARZ3FHCRimtNCVu2evNaaBkWNSK4fKjoMCtb5CNTLyg9ZQoXTDfcu4LFM",
    "refund": "3yvsvRXiV5Zue4rLPWhrBUpZMRyjJc2mAKsDHyzFLvTn7SxpV4ExqKh6rNMiT4Z9JusbzHsZB9ZFzTM9fsApYYpW"
  }
} as const;

export type Deployment = (typeof DEPLOYMENTS)[NetworkId];

/** Narrows an untrusted string — a query param, localStorage — to a network. */
export function asNetwork(value: unknown): NetworkId | null {
  return typeof value === 'string' && (NETWORK_IDS as readonly string[]).includes(value)
    ? (value as NetworkId)
    : null;
}

/** Same, but never fails: anything unrecognised becomes the default. */
export function networkOrDefault(value: unknown): NetworkId {
  return asNetwork(value) ?? DEFAULT_NETWORK;
}

/** True once the program and accounts for this network actually exist. */
export function isConfigured(net: NetworkId): boolean {
  const d = DEPLOYMENTS[net];
  return Boolean(d.programId && d.usdcMint && d.resolver && d.treasury);
}

export function deployment(net: NetworkId = DEFAULT_NETWORK): Deployment {
  if (!isConfigured(net)) {
    throw new Error(`El programa no está desplegado en ${net}. Corré scripts/solana-init.mts.`);
  }
  return DEPLOYMENTS[net];
}
