// GENERATED by scripts/write-deployments-module.mjs — do not edit.
// Source of truth: deployments.json at the repo root, written by
// scripts/solana-init.mts.

export type NetworkId = 'devnet';

export const NETWORK_IDS = ['devnet'] as const;

export const DEFAULT_NETWORK: NetworkId = 'devnet';

export const DEPLOYMENTS = {
  devnet: {
    id: 'devnet',
    rpcUrl: 'https://api.devnet.solana.com',
    deployedAt: '2026-10-04T15:35:00.668Z',
    /** anchor/programs/changuito_escrow. */
    programId: '9A2PXJafYxym4i8ah1QFQZngqz2j7rQh8xQX2eXB2wC9',
    /** The escrow's Config PDA: resolver, treasury and mint. */
    config: 'BfMWiygm3XRab8xbJC355rxRZ4DFYqR2vyi1gjSjWyTQ',
    /** Our devnet USDC. The resolver is its mint authority (the faucet). */
    usdcMint: '9rYNCiaaKQ5rT1QR8Ar6FJVUr7gnwZy3RYAT6MtAtdMM',
    usdcDecimals: 6,
    usdcCode: 'USDC',
    /** Backend hot key: signs settle, refund and faucet mints. */
    resolver: 'AgTnHC9dmyuzjwp3oCRzaYrZbgeXD4tC2uSXmKhiyqQ5',
    /** Where a settled order's USDC ends up. The app never signs for it. */
    treasury: 'EV5c3mjEHBtTU6JmX31eLsfKX5zPgMVDEiKDhqjApZPS',
    treasuryToken: 'HVsDJbwmsa2oTUpddQMSSUzKF6Z4PvQRU96d7n95owxa',
  },
} as const;

/** Signatures that prove the deployment: deploy, initialize, smoke settle/refund. */
export const EVIDENCE = {
  "deploy": "3f3caazBpPsDmcvQnKzGgdM7H1GPMeNiZoD6Z8yq7H8JX8tdrEmfXMA2gBuDSNBbRqCsq51KF6VtLCG4SQ91YjmC",
  "initialize": "3mWgS3g9iCju1J9p8s6563KRQfG3juVCX2mwFqURJB2oYVWzvAimMgPqxjMNsJUFY64unGUtBcwsyzsfoWUu7Xj2",
  "smoke": {
    "fund": "2bahH3CVovSMEKLELkjJUYq1JTtnJkLcxUGSHVc4UaiSDPj5MT2cB1SCVJAX4uJfoP4z5HM2rUDryCmmEqa6Cjux",
    "settleOpen": "5Hw7m8aq638nYbY9MY5C8bDs4XC4AjqNAESgEVpErLMcYvkMkdmrghHUtQkR2k9Ex7XfWFzVnPsyHztzmuJJFNPr",
    "settle": "z5Qq1C15CTsqC94R3mGrgEzqr29LNstTmFm4mEr3nVb3gY2Yna7LhL3mG2EoPuosiun9NLAKG77E3tSPCFjwew8",
    "refundOpen": "C7VcfqHYVTNAkjP8T8isTWcfVhfewHgU4U8ZZQXEDnoMtLvLoiDrVf8Te4UwKS5zg7D45PdKbfmvrK8mVTgomNz",
    "refund": "5GtMF7JvPdcog9d7oebhdwtgfw45yPY8Nh6mS6TE5pdXmBXcYad7saFPHsxriqUry4fYLAWqqXboKAM5HjFQA47e"
  }
} as const;

export type Deployment = (typeof DEPLOYMENTS)[NetworkId];

/** Narrows an untrusted string — a query param, localStorage — to a network. */
export function asNetwork(value: unknown): NetworkId | null {
  return typeof value === 'string' && (NETWORK_IDS as readonly string[]).includes(value)
    ? (value as NetworkId)
    : null;
}

/** Same, but never fails: anything unrecognised becomes the default. */
export function networkOrDefault(value: unknown): NetworkId {
  return asNetwork(value) ?? DEFAULT_NETWORK;
}

/** True once the program and accounts for this network actually exist. */
export function isConfigured(net: NetworkId): boolean {
  const d = DEPLOYMENTS[net];
  return Boolean(d.programId && d.usdcMint && d.resolver && d.treasury);
}

export function deployment(net: NetworkId = DEFAULT_NETWORK): Deployment {
  if (!isConfigured(net)) {
    throw new Error(`El programa no está desplegado en ${net}. Corré scripts/solana-init.mts.`);
  }
  return DEPLOYMENTS[net];
}
